// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMA.Infrastructure.Persistence;

#nullable disable

namespace UMA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819133950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UMA.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4c13bdf2-12cb-486d-bd2c-24c23d916a6d"),
                            CreatedAt = new DateTime(2025, 8, 19, 13, 39, 49, 964, DateTimeKind.Utc).AddTicks(7937),
                            Email = "marcus.kok@email.com",
                            FirstName = "Marcus",
                            LastName = "Kok",
                            Password = "$2b$10$LB9HbCHkEleGIDuoRrpyGe58krqx4bMjIF.a5SJWqPaRy7saOFhoi",
                            ProfilePictureUrl = "",
                            UpdatedAt = new DateTime(2025, 8, 19, 13, 39, 49, 877, DateTimeKind.Utc).AddTicks(944)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
